const Products = [
  {
    id: 182,
    name: "Freezer",
    description: "a freezer to freeze stuff",
    number: 1234,
    rating: 4.49,
    beforePrice: 900,
    price: 600,
    category: "/appliance/freezer/",
    mainCategory: "appliance",
    subCategory: ["freezer"],
    image: ["image", "image2"],
    keywords: ["freezer", "cold"],
  },
  {
    id: 183,
    name: "cooler",
    description: "a cooler to cool stuff",
    number: 6123,
    rating: 2.13,
    beforePrice: 600,
    price: 300,
    category: "/appliance/cooler/",
    mainCategory: "appliance",
    subCategory: ["cooler"],
    image: ["image", "image2"],
    keywords: ["cooler", "cold"],
  },
  {
    id: 156,
    name: "Cpu",
    description: "a computation processing unit",
    number: 1234,
    rating: 4.5,
    beforePrice: 2145,
    price: 2100,
    category: "/computer/computerComponents/cpu/",
    mainCategory: "computer",
    subCategory: ["computerComponents", "cpu"],
    image: ["image", "image2"],
  },
];

export default Products;
